<a href="https://colab.research.google.com/github/bikash119/learn_tensorflow/blob/main/learn_tf_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning outcome
1. Understand and play with tensors.
2. Make my Feet wet with Tensorflow.
3. Manipulating tensors and fix / understand any errors on the way.
4. Using `@tf.function`

In [ ]:
import tensorflow as tf

print(f" Current version of tensorflow : {tf.__version__}")

 Current version of tensorflow : 2.12.0


In [ ]:
# Create a scalar ( Rank 0 tensor)
scalar = tf.constant(7)
print(f" Scalar value : {scalar}")
print(f" Shape of the scalar value : {scalar.shape}")
print(f" Number of dimensions in scalar : {scalar.ndim}")

 Scalar value : 7
 Shape of the scalar value : ()
 Number of dimensions in scalar : 0


In [ ]:
# create a vector
vector = tf.constant([10
                     ,10])
print(f" vector value : {vector}")
print(f" Shape of the vector value : {vector.shape}")
print(f" Number of dimensions in vector : {vector.ndim}")

 vector value : [10 10]
 Shape of the vector value : (2,)
 Number of dimensions in vector : 1


In [ ]:
# create a matrix
matrix = tf.constant([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {matrix}")
print(f" Shape of the matrix value : {matrix.shape}")
print(f" Number of dimensions in matrix : {matrix.ndim}")

 matrix value : [[10 10]
 [20 20]
 [20 20]]
 Shape of the matrix value : (3, 2)
 Number of dimensions in matrix : 2


In [ ]:
_3d_matrix = tf.constant([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {_3d_matrix}")
print(f" Shape of the _3d_matrix value : {_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {_3d_matrix.ndim}")

 _3d_matrix value : [[[10 10 10 10]
  [10 10 10 10]]

 [[20 20 20 20]
  [20 20 20 20]]

 [[30 30 30 30]
  [30 30 30 30]]]
 Shape of the _3d_matrix value : (3, 2, 4)
 Number of dimensions in _3d_matrix : 3


Similartity and difference between `tf.Variable()` and `tf.constant()`

In [ ]:
# Create a scalar ( Rank 0 tensor)
const_scalar = tf.constant(7)
print(f" Scalar value : {const_scalar}")
print(f" Shape of the scalar value : {const_scalar.shape}")
print(f" Number of dimensions in scalar : {const_scalar.ndim}")

var_scalar = tf.Variable(7)
print(f" Scalar value : {var_scalar}")
print(f" Shape of the scalar value : {var_scalar.shape}")
#print(f" Number of dimensions in scalar : {var_scalar.ndim}")
print(f" *"*50,sep="\n")
# create a vector
const_vector = tf.constant([10
                     ,10])
print(f" vector value : {const_vector}")
print(f" Shape of the vector value : {const_vector.shape}")
print(f" Number of dimensions in vector : {const_vector.ndim}")

var_vector = tf.Variable([10
                     ,10])
print(f" vector value : {var_vector}")
print(f" Shape of the vector value : {var_vector.shape}")
#print(f" Number of dimensions in vector : {var_vector.ndim}")
print(f" *"*50,sep="\n")
# create a matrix
const_matrix = tf.constant([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {const_matrix}")
print(f" Shape of the matrix value : {const_matrix.shape}")
print(f" Number of dimensions in matrix : {const_matrix.ndim}")

var_matrix = tf.Variable([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {var_matrix}")
print(f" Shape of the matrix value : {var_matrix.shape}")
#print(f" Number of dimensions in matrix : {var_matrix.ndim}")
print(f" *"*50,sep="\n")
const_3d_matrix = tf.constant([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {_3d_matrix}")
print(f" Shape of the _3d_matrix value : {_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {_3d_matrix.ndim}")
print(f" Number of dimensions in _3d_matrix : {tf.size(_3d_matrix)}")

var_3d_matrix = tf.Variable([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {var_3d_matrix}")
print(f" Shape of the _3d_matrix value : {var_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {tf.size(var_3d_matrix)}")
print(f" *"*50,sep="\n")

 Scalar value : 7
 Shape of the scalar value : ()
 Number of dimensions in scalar : 0
 Scalar value : <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>
 Shape of the scalar value : ()
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 vector value : [10 10]
 Shape of the vector value : (2,)
 Number of dimensions in vector : 1
 vector value : <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>
 Shape of the vector value : (2,)
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 matrix value : [[10 10]
 [20 20]
 [20 20]]
 Shape of the matrix value : (3, 2)
 Number of dimensions in matrix : 2
 matrix value : <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 10],
       [20, 20],
       [20, 20]], dtype=int32)>
 Shape of the matrix value : (3, 2)
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

In [ ]:
const_scalar[0] = 30

TypeError: ignored

In [ ]:
var_scalar.assign(9)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=9>

Generate Randome tensors

In [ ]:
random_gen_1 = tf.random.Generator.from_seed(seed=42)
random_gen_2 = tf.random.Generator.from_seed(seed=42)
print(f" Are the generators same: {random_gen_1 == random_gen_2}")
random_tensor_1 = random_gen_1.normal((3,2,4))
random_tensor_2 = random_gen_2.normal((3,2,4))

print(f" Are the tensors from 2 generators same : {random_tensor_1 == random_tensor_2}")


 Are the generators same: False
 Are the tensors from 2 generators same : [[[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]]


Global and operation-level seed
`tf.random.set_seed()` sets the global seed, and the `seed` parameter in `tf.random.shuffle(seed=42)` set the operation level seed.

In [ ]:
# Global seed
tf.random.set_seed(42)

# operation level seed
tf.random.shuffle(const_matrix,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20],
       [20, 20]], dtype=int32)>

Other ways to make tensors

In [ ]:
tf.ones(dtype=tf.dtypes.int32,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [ ]:
tf.zeros(dtype=tf.dtypes.float32,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Adding dimension to a tensor

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.random.shuffle(value=const_matrix,seed=42)
rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)
print(f" Rank of rank_2_tensor : {rank_2_tensor.shape}")
print(f" Rank of rank_3_tensor : {rank_3_tensor.shape}")

 Rank of rank_2_tensor : (3, 2)
 Rank of rank_3_tensor : (3, 2, 1)


In [ ]:
rank_3_tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[20],
        [20]],

       [[10],
        [10]],

       [[20],
        [20]]], dtype=int32)>

Tensor operations
1. Addition
2. Substraction
3. Multiplication
4. Matrix Multiplication

In [ ]:
random_tensor = tf.constant([ [[10,10,10,10],[10,10,10,10],[10,10,10,10],[10,10,10,10],[10,10,10,10]]
                             ,[[20,20,20,20],[20,20,20,20],[20,20,20,20],[20,20,20,20],[20,20,20,20]]
                             ,[[30,30,30,30],[30,30,30,30],[30,30,30,30],[30,30,30,30],[30,30,30,30]]
                            ],dtype=tf.dtypes.float32,shape=(3,5,4))
print(f" Add 25 to random_tensor : {tf.add(random_tensor,25)}")
print(f" Substract 25 from random_tensor : {tf.subtract (random_tensor,25)}")
print(f" Multiply 25 to random_tensor : {tf.add (random_tensor,25)}")

 Add 25 to random_tensor : [[[35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]]

 [[45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]]

 [[55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]]]
 Substract 25 from random_tensor : [[[-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]]

 [[ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]]

 [[  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]]]
 Multiply 25 to random_tensor : [[[35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]]

 [[45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]]

 [[55. 55. 55. 55.]
  [55. 55.

Matrix Multiplication

In [ ]:
tensor_1 = tf.constant(value=[[10,10,10],[10,10,10]],dtype=tf.dtypes.int32)
tensor_2 = tf.constant(value=[[10,10],[10,10],[10,10]],dtype=tf.dtypes.int32)
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 300],
       [300, 300]], dtype=int32)>

Finding the max, min, mean, sum, abs

In [ ]:
# create a tensor with 50 random values between 0 and 100
import numpy as np
E = tf.constant(np.random.randint(low=-10,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 34, -10,  45,  97,  58,  81,  25,   0,  39,   2,  94,   2,  73,
        -3,  37,  27,  68,  16,  99,   1,  85,  47,  63,  79,  -4,  66,
        43,  87,  94,  96,  43,  60,  89,  63,  -9,  40,  20,  12,  33,
         9,  -1,  24,  47,  15,  -1,  40,  78,  82,  35,  43])>

In [ ]:
# Min
print(f" Minimum value in E : {tf.reduce_min(E)}")
# Max
print(f" Max value in E : {tf.reduce_max(E)}")
# Mean
print(f" Mean value in E : {tf.reduce_mean(E)}")
#abs
print(f" Abs value of E[10] :{tf.abs(E[10])}")

 Minimum value in E : 2
 Max value in E : 99
 Mean value in E : 55
 Abs value of E[10] :49
