<a href="https://colab.research.google.com/github/bikash119/learn_tensorflow/blob/main/learn_tf_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning outcome
1. Understand and play with tensors.
2. Make my Feet wet with Tensorflow.
3. Manipulating tensors and fix / understand any errors on the way.
4. Using `@tf.function`

In [1]:
import tensorflow as tf

print(f" Current version of tensorflow : {tf.__version__}")

 Current version of tensorflow : 2.12.0


In [2]:
# Create a scalar ( Rank 0 tensor)
scalar = tf.constant(7)
print(f" Scalar value : {scalar}")
print(f" Shape of the scalar value : {scalar.shape}")
print(f" Number of dimensions in scalar : {scalar.ndim}")

 Scalar value : 7
 Shape of the scalar value : ()
 Number of dimensions in scalar : 0


In [3]:
# create a vector
vector = tf.constant([10
                     ,10])
print(f" vector value : {vector}")
print(f" Shape of the vector value : {vector.shape}")
print(f" Number of dimensions in vector : {vector.ndim}")

 vector value : [10 10]
 Shape of the vector value : (2,)
 Number of dimensions in vector : 1


In [4]:
# create a matrix
matrix = tf.constant([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {matrix}")
print(f" Shape of the matrix value : {matrix.shape}")
print(f" Number of dimensions in matrix : {matrix.ndim}")

 matrix value : [[10 10]
 [20 20]
 [20 20]]
 Shape of the matrix value : (3, 2)
 Number of dimensions in matrix : 2


In [5]:
_3d_matrix = tf.constant([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {_3d_matrix}")
print(f" Shape of the _3d_matrix value : {_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {_3d_matrix.ndim}")

 _3d_matrix value : [[[10 10 10 10]
  [10 10 10 10]]

 [[20 20 20 20]
  [20 20 20 20]]

 [[30 30 30 30]
  [30 30 30 30]]]
 Shape of the _3d_matrix value : (3, 2, 4)
 Number of dimensions in _3d_matrix : 3


Similartity and difference between `tf.Variable()` and `tf.constant()`

In [6]:
# Create a scalar ( Rank 0 tensor)
const_scalar = tf.constant(7)
print(f" Scalar value : {const_scalar}")
print(f" Shape of the scalar value : {const_scalar.shape}")
print(f" Number of dimensions in scalar : {const_scalar.ndim}")

var_scalar = tf.Variable(7)
print(f" Scalar value : {var_scalar}")
print(f" Shape of the scalar value : {var_scalar.shape}")
#print(f" Number of dimensions in scalar : {var_scalar.ndim}")
print(f" *"*50,sep="\n")
# create a vector
const_vector = tf.constant([10
                     ,10])
print(f" vector value : {const_vector}")
print(f" Shape of the vector value : {const_vector.shape}")
print(f" Number of dimensions in vector : {const_vector.ndim}")

var_vector = tf.Variable([10
                     ,10])
print(f" vector value : {var_vector}")
print(f" Shape of the vector value : {var_vector.shape}")
#print(f" Number of dimensions in vector : {var_vector.ndim}")
print(f" *"*50,sep="\n")
# create a matrix
const_matrix = tf.constant([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {const_matrix}")
print(f" Shape of the matrix value : {const_matrix.shape}")
print(f" Number of dimensions in matrix : {const_matrix.ndim}")

var_matrix = tf.Variable([
                      [10,10]
                     ,[20,20]
                     ,[20,20]])
print(f" matrix value : {var_matrix}")
print(f" Shape of the matrix value : {var_matrix.shape}")
#print(f" Number of dimensions in matrix : {var_matrix.ndim}")
print(f" *"*50,sep="\n")
const_3d_matrix = tf.constant([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {_3d_matrix}")
print(f" Shape of the _3d_matrix value : {_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {_3d_matrix.ndim}")
print(f" Number of dimensions in _3d_matrix : {tf.size(_3d_matrix)}")

var_3d_matrix = tf.Variable([
                           [[10,10,10,10],[10,10,10,10]]
                          ,[[20,20,20,20],[20,20,20,20]]
                          ,[[30,30,30,30],[30,30,30,30]]
                        ])
print(f" _3d_matrix value : {var_3d_matrix}")
print(f" Shape of the _3d_matrix value : {var_3d_matrix.shape}")
print(f" Number of dimensions in _3d_matrix : {tf.size(var_3d_matrix)}")
print(f" *"*50,sep="\n")

 Scalar value : 7
 Shape of the scalar value : ()
 Number of dimensions in scalar : 0
 Scalar value : <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>
 Shape of the scalar value : ()
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 vector value : [10 10]
 Shape of the vector value : (2,)
 Number of dimensions in vector : 1
 vector value : <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>
 Shape of the vector value : (2,)
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 matrix value : [[10 10]
 [20 20]
 [20 20]]
 Shape of the matrix value : (3, 2)
 Number of dimensions in matrix : 2
 matrix value : <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 10],
       [20, 20],
       [20, 20]], dtype=int32)>
 Shape of the matrix value : (3, 2)
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

In [8]:
const_scalar[0] = 30

TypeError: ignored

In [9]:
var_scalar.assign(9)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=9>

Generate Randome tensors

In [10]:
random_gen_1 = tf.random.Generator.from_seed(seed=42)
random_gen_2 = tf.random.Generator.from_seed(seed=42)
print(f" Are the generators same: {random_gen_1 == random_gen_2}")
random_tensor_1 = random_gen_1.normal((3,2,4))
random_tensor_2 = random_gen_2.normal((3,2,4))

print(f" Are the tensors from 2 generators same : {random_tensor_1 == random_tensor_2}")


 Are the generators same: False
 Are the tensors from 2 generators same : [[[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]]


Global and operation-level seed
`tf.random.set_seed()` sets the global seed, and the `seed` parameter in `tf.random.shuffle(seed=42)` set the operation level seed.

In [11]:
# Global seed
tf.random.set_seed(42)

# operation level seed
tf.random.shuffle(const_matrix,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20],
       [20, 20]], dtype=int32)>

Other ways to make tensors

In [12]:
tf.ones(dtype=tf.dtypes.int32,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [13]:
tf.zeros(dtype=tf.dtypes.float32,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Adding dimension to a tensor

In [14]:
# Create a rank 2 tensor
rank_2_tensor = tf.random.shuffle(value=const_matrix,seed=42)
rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)
print(f" Rank of rank_2_tensor : {rank_2_tensor.shape}")
print(f" Rank of rank_3_tensor : {rank_3_tensor.shape}")

 Rank of rank_2_tensor : (3, 2)
 Rank of rank_3_tensor : (3, 2, 1)


In [15]:
rank_3_tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[20],
        [20]],

       [[10],
        [10]],

       [[20],
        [20]]], dtype=int32)>

Tensor operations
1. Addition
2. Substraction
3. Multiplication
4. Matrix Multiplication

In [16]:
random_tensor = tf.constant([ [[10,10,10,10],[10,10,10,10],[10,10,10,10],[10,10,10,10],[10,10,10,10]]
                             ,[[20,20,20,20],[20,20,20,20],[20,20,20,20],[20,20,20,20],[20,20,20,20]]
                             ,[[30,30,30,30],[30,30,30,30],[30,30,30,30],[30,30,30,30],[30,30,30,30]]
                            ],dtype=tf.dtypes.float32,shape=(3,5,4))
print(f" Add 25 to random_tensor : {tf.add(random_tensor,25)}")
print(f" Substract 25 from random_tensor : {tf.subtract (random_tensor,25)}")
print(f" Multiply 25 to random_tensor : {tf.add (random_tensor,25)}")

 Add 25 to random_tensor : [[[35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]]

 [[45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]]

 [[55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]
  [55. 55. 55. 55.]]]
 Substract 25 from random_tensor : [[[-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]
  [-15. -15. -15. -15.]]

 [[ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]
  [ -5.  -5.  -5.  -5.]]

 [[  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]
  [  5.   5.   5.   5.]]]
 Multiply 25 to random_tensor : [[[35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]
  [35. 35. 35. 35.]]

 [[45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]
  [45. 45. 45. 45.]]

 [[55. 55. 55. 55.]
  [55. 55.

Matrix Multiplication

In [17]:
tensor_1 = tf.constant(value=[[10,10,10],[10,10,10]],dtype=tf.dtypes.int32)
tensor_2 = tf.constant(value=[[10,10],[10,10],[10,10]],dtype=tf.dtypes.int32)
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[300, 300],
       [300, 300]], dtype=int32)>

Finding the max, min, mean, sum, abs

In [18]:
# create a tensor with 50 random values between 0 and 100
import numpy as np
E = tf.constant(np.random.randint(low=-10,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 93, -10,  25,   0,  29,  85,  51,  21,  20,  75,  97,   3,  36,
        27,  81,  74,  35,  62,  51, -10,  74,  75,  28,  93,  54,  64,
         7,  17,  52,  40,  92,  37,  86,  59,  41,  85,  65,  -1,   2,
        57,  77,  90,  50,  50,  76,  61,  -9,  30,  44,  41])>

In [19]:
# Min
print(f" Minimum value in E : {tf.reduce_min(E)}")
# Max
print(f" Max value in E : {tf.reduce_max(E)}")
# Mean
print(f" Mean value in E : {tf.reduce_mean(E)}")
#abs
print(f" Abs value of E[10] :{tf.abs(E[10])}")

 Minimum value in E : -10
 Max value in E : 97
 Mean value in E : 47
 Abs value of E[10] :97


In [20]:
# Finding positional max and min
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.14919227, 0.95801968, 0.55568926, 0.68971043, 0.2408837 ,
       0.84069223, 0.845783  , 0.60637532, 0.3194909 , 0.64088485,
       0.34984159, 0.45138568, 0.26335132, 0.86655589, 0.25576287,
       0.89908755, 0.94338073, 0.52647197, 0.218997  , 0.03030664,
       0.38761528, 0.40503161, 0.7304157 , 0.15104655, 0.83793809,
       0.72215718, 0.81346129, 0.06280607, 0.32745998, 0.2437112 ,
       0.13957961, 0.43133419, 0.72225295, 0.47801708, 0.75857079,
       0.13139   , 0.42433454, 0.43828962, 0.37394905, 0.36482609,
       0.80009673, 0.11636296, 0.51419319, 0.30901844, 0.80080883,
       0.55426808, 0.45055079, 0.20378153, 0.56985891, 0.70095548])>

In [21]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [22]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [23]:
print(f" The maximum value of F is at index : {tf.argmax(F).numpy()}")
print(f" The minimum value of F is at index : {tf.argmin(F).numpy()}")
print(f" The maximum value of F is at index : {tf.argmax(F).numpy()} and the value is {F[tf.argmax(F).numpy()].numpy():.5f}")
print(f" The maximum value of F is at index : {tf.argmin(F).numpy()} and the value is {F[tf.argmin(F).numpy()].numpy():.5f}")

 The maximum value of F is at index : 1
 The minimum value of F is at index : 19
 The maximum value of F is at index : 1 and the value is 0.95802
 The maximum value of F is at index : 19 and the value is 0.03031


Manipulating `tf.Variable` tensors

In [24]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [25]:
I.assign([0,1,3,2,60])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  3,  2, 60])>

In [26]:
I.assign_add([0,1,3,2,60])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([  0,   2,   6,   4, 120])>

By default tensors have `float32` and numpy array have `float64` as datatype.
Learn more about `args` and `kwargs` at [here](https://realpython.com/python-kwargs-and-args/)

Finding access to GPU

In [27]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [28]:
!nvidia-smi

Sun Jun 25 21:19:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    30W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Exercises



1. Shape of Tensor : The number of elements in each dimension.
2. Rank : The number of dimension
3. Size : The number of elements in tensor



In [30]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
#Find the shape, rank and size of the tensors you created in 1
vector = tf.constant([0,10])
scalar = tf.constant(10)
matrix = tf.constant([ [10,10]
                      ,[20,20]
                    ])


print(f" Printing Shape, Rank and Size of vector ....")
print(f" Shape of vector : {vector.shape}")
print(f" Rank of vector : {vector.ndim}")
print(f" Size of vector : {tf.size(vector)}")


print(f" Printing Shape, Rank and Size of scalar ....")
print(f" Shape of scalar : {scalar.shape}")
print(f" Rank of scalar : {scalar.ndim}")
print(f" Size of scalar : {tf.size(vector)}")

print(f" Printing Shape, Rank and Size of matrix ....")
print(f" Shape of matrix : {matrix.shape}")
print(f" Rank of matrix : {matrix.ndim}")
print(f" Size of matrix : {tf.size(matrix)}")


 Printing Shape, Rank and Size of vector ....
 Shape of vector : (2,)
 Rank of vector : 1
 Size of vector : 2
 Printing Shape, Rank and Size of scalar ....
 Shape of scalar : ()
 Rank of scalar : 0
 Size of scalar : 2
 Printing Shape, Rank and Size of matrix ....
 Shape of matrix : (2, 2)
 Rank of matrix : 2
 Size of matrix : 4


In [41]:
#3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
#4. Multiply the two tensors you created in 3 using matrix multiplication.
#5. Multiply the two tensors you created in 3 using dot product.
gen = tf.random.Generator.from_seed(42)
random_1 = gen.normal(shape=(3,500))
random_2 = gen.normal(shape=(3,500))

def print_srs(tensor:tf.Tensor):
  print(f" Shape : {tensor.shape}")
  print(f" Rank : {tensor.ndim}")
  print(f" Size : {tf.size(tensor)}")

print_srs(random_1)

#matrix multiplication
# matmul_result = tf.matmul(random_1,random_2)
# print(f" matmul result: {matmul_result}")

# Dot Product
dot_result = random_1 * random_2
print(f" dot result : {dot_result}")
print_srs(dot_result)

 Shape : (3, 500)
 Rank : 2
 Size : 1500
 dot result : [[ 0.6169889  -0.01782765  0.05413234 ...  0.00294868  0.3637814
  -0.03261912]
 [-0.39358786 -1.0440075   0.04571367 ... -0.5981697  -0.13508786
   0.41872486]
 [ 0.19866256 -1.2366698  -0.12448977 ...  0.3734429  -0.16223323
  -0.13076478]]
 Shape : (3, 500)
 Rank : 2
 Size : 1500


In [43]:
#6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
#7. Find the min and max values of the tensor you created in 6.
gen = tf.random.Generator.from_seed(42)
random_3 = gen.normal(shape=(224,224,3))

print(f" The max value in random_3 :{ tf.reduce_max(random_3)}")
print(f" The min value in random_3 :{ tf.reduce_min(random_3)}")

 The max value in random_3 :4.403286457061768
 The min value in random_3 :-4.848316192626953


In [44]:
#8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
gen = tf.random.Generator.from_seed(42)
random_4 = gen.normal(shape=(1,224,224,3))
print_srs(random_4)
print_srs(tf.squeeze(random_4))

 Shape : (1, 224, 224, 3)
 Rank : 4
 Size : 150528
 Shape : (224, 224, 3)
 Rank : 3
 Size : 150528


In [47]:
#9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
random_5 = tf.random.shuffle(np.random.random(10))
print_srs(random_5)
print(f" Index of maximum value : {tf.argmax(random_5).numpy()} and the value is {tf.reduce_max(random_5)}")
print(f" Is the max value same as this? : {random_5[tf.argmax(random_5).numpy()].numpy()}")

 Shape : (10,)
 Rank : 1
 Size : 10
 Index of maximum value : 8 and the value is 0.8703344228800377
 Is the max value same as this? : 0.8703344228800377
