<a href="https://colab.research.google.com/github/bikash119/learn_tensorflow/blob/main/timeseries_tf_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn windowing

## Simple Dataset

In [1]:
import tensorflow as tf

In [2]:
dataset= tf.data.Dataset.range(10)
for val in dataset:
  print(val.numpy(),end=" ")

0 1 2 3 4 5 6 7 8 9 

In [4]:
window=dataset.window(5,shift=1,drop_remainder=True)
for val in window:
  print([item.numpy() for item in val])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [6]:
flat_dataset= window.flat_map(lambda dataset:dataset.batch(5))
for item in flat_dataset:
  print(item.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [21]:
features_labels = flat_dataset.map(lambda col: (col[:-1],col[-1]))
for x,y in features_labels:


[(array([0, 1, 2, 3]), 4),
 (array([1, 2, 3, 4]), 5),
 (array([2, 3, 4, 5]), 6),
 (array([3, 4, 5, 6]), 7),
 (array([4, 5, 6, 7]), 8),
 (array([5, 6, 7, 8]), 9)]